(() => {
  const $ = selector => document.querySelector(selector);
  const esc = window.demoEscape;
  const paths = {
    heart: 'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',
    comment: 'M21 11.5a8.4 8.4 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.4 8.4 0 0 1-3.8-.9L3 21l1.9-5.7a8.4 8.4 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6A8.4 8.4 0 0 1 12.5 3H13a8.5 8.5 0 0 1 8 8v.5Z',
    share: 'm22 2-7 20-4-9-9-4 20-7ZM22 2 11 13',
    repeat: 'm17 2 4 4-4 4M3 11V8a2 2 0 0 1 2-2h16M7 22l-4-4 4-4m14-1v3a2 2 0 0 1-2 2H3',
    lock: 'M6 10V7a6 6 0 0 1 12 0v3M4 10h16v12H4V10Zm8 5v3',
    home: 'm3 10 9-8 9 8v12h-7v-8h-4v8H3V10Z',
    back: 'm14 5-7 7 7 7',
    bookmark: 'M5 3h14v19l-7-5-7 5V3Z',
    plus: 'M12 5v14M5 12h14',
    search: 'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z',
    camera: 'M3 7h4l2-3h6l2 3h4v14H3V7Zm13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z'
  };
  const icon = name => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name] || paths.lock}"/></svg>`;
  let profile = {};
  try { profile = JSON.parse(localStorage.getItem('instagram_profile') || '{}'); } catch {}
  const username = esc(profile.username || 'perfil_demo');
  const names = ['fer*****','lim*****','ric*****','ana*****','sm.*****','vit*****','jp0*****','cel*****','who*****','tiq*****','mar*****','bia*****','leo*****','gui*****','isa*****'];
  const places = ['São Paulo, Brasil','Rio de Janeiro, Brasil','Localização ilustrativa','Belo Horizonte, Brasil','Curitiba, Brasil'];
  const avatar = (i, locked = true) => `<span class="avatar hue-${i % 5}"><span class="portrait"></span>${locked ? `<span class="avatar-lock">${icon('lock')}</span>` : ''}</span>`;
  const nav = () => `<nav class="bottom-nav" aria-label="Navegação"><a href="feed.html" aria-label="Feed">${icon('home')}</a><button data-notice="Busca demonstrativa" aria-label="Pesquisar">${icon('search')}</button><a href="paginafinal.html" aria-label="Demonstração VIP">${icon('plus')}</a><a href="direct.html" aria-label="Direct">${icon('share')}</a><a href="index.html" aria-label="Escolher perfil">${avatar(2, false)}</a></nav>`;
  const restricted = (i, label = 'Conteúdo restrito') => `<div class="restricted hue-${i % 5}"><div class="scene"><i></i><b></b></div><div class="restriction">${icon('lock')}<strong>${label}</strong><small>Prévia fictícia</small><a href="paginafinal.html">Ver demonstração</a></div></div>`;
  const feed = () => `<div class="social-shell"><header class="social-header"><span class="wordmark">Instagram</span><div><button data-notice="Notificações demonstrativas" aria-label="Notificações">${icon('heart')}</button><a href="direct.html" aria-label="Abrir Direct">${icon('share')}<i class="badge">4</i></a></div></header><section class="stories" aria-label="Stories fictícios">${[username,...names.slice(0,7)].map((name,i)=>`<a href="paginafinal.html"><span class="story-ring">${avatar(i,i>0)}</span><small>${i ? name : 'Seu story'}</small></a>`).join('')}</section><p class="context">Feed ilustrativo de @${username} · pessoas e locais fictícios</p><main id="posts-container">${names.map((name,i)=>`<article class="post"><header>${avatar(i)}<div><strong>${name}</strong><small>${places[i%5]}</small></div><button aria-label="Opções do post" data-notice="Post demonstrativo">•••</button></header>${restricted(i)}<div class="post-actions"><button data-like aria-label="Curtir" aria-pressed="false">${icon('heart')}</button><button data-comment aria-label="Comentar">${icon('comment')}</button><button data-repost aria-label="Republicar" aria-pressed="false">${icon('repeat')}</button><button data-share aria-label="Compartilhar">${icon('share')}</button><button class="save" data-save aria-label="Salvar" aria-pressed="false">${icon('bookmark')}</button></div><div class="post-info"><strong class="like-count">${125+i*37} curtidas</strong><p><b>${name}</b> Um registro para guardar ✨</p><button data-comment class="muted">Ver todos os ${8+i*3} comentários</button><div class="comments"></div><time>há 1 dia</time></div></article>`).join('')}</main>${nav()}</div>`;
  const direct = () => `<div class="social-shell"><header class="social-header"><a href="feed.html" aria-label="Voltar">${icon('back')}</a><strong>${username}</strong><button data-notice="Nova mensagem demonstrativa" aria-label="Nova mensagem">${icon('plus')}</button></header><main class="direct-main"><div class="search-bar">${icon('search')} Pergunte à Meta AI ou pesquise</div><div class="section-title"><h1>Mensagens</h1><span>Pedidos · 4</span></div><p class="context">Conversas fictícias da demonstração</p>${names.slice(0,10).map((name,i)=>`<button class="conversation" data-chat="${i}">${avatar(i)}<span><strong>${name}</strong><small>${['enviou uma mensagem · Agora','Você: kkkkk tá doido · 2 min','enviou uma foto · 14 min','Você curtiu uma mensagem · 1 h','áudio 0:14 · 3 h','enviou um story · 5 h','Você: bora? · ontem','mensagem temporária · ontem','reagiu à sua mensagem · 2 d','enviou um reel · 3 d'][i]}</small></span>${icon('camera')}</button>`).join('')}<div class="direct-cta">${icon('lock')}<h2>Conteúdo restrito</h2><p>Explore o fluxo VIP com mensagens de exemplo. Nenhuma conversa privada é acessada.</p><a class="primary" href="paginafinal.html">Ver demonstração VIP</a></div></main>${nav()}</div>`;
  const cta = () => `<main class="sales"><a href="feed.html" class="back-link">← Voltar ao feed</a><img class="brand" src="images/logo-vert-transparente.png" alt="Logo do projeto"><h1>Explore a experiência<br><em>VIP</em> de demonstração</h1><section class="profile-card">${avatar(2,false)}<div><strong>@${username}</strong><p>${esc(profile.full_name || 'Perfil de demonstração')}</p></div><div class="stats"><span><b>${esc(profile.media_count ?? '—')}</b>posts</span><span><b>${esc(profile.follower_count ?? '—')}</b>seguidores</span><span><b>${esc(profile.following_count ?? '—')}</b>seguindo</span></div></section><div class="purple-panel"><b>Prévia pronta para explorar</b><p>Veja como funciona o fluxo completo com dados fictícios.</p></div><p class="down">↓</p>${[['Mídias ilustrativas','Uma prévia visual de fotos e vídeos fictícios.'],['Localização de exemplo','Locais ilustrativos, sem rastrear nenhuma pessoa.'],['Stories e posts','Explore os estados de conteúdo restrito da interface.'],['Mensagens do Direct','Converse com personagens fictícios da demonstração.']].map(([title,desc],i)=>`<section class="feature"><h2>${icon(i===3?'comment':'lock')}${title}</h2><p>${desc}</p><div class="tiles">${restricted(i)}${restricted(i+1)}${restricted(i+2)}</div></section>`).join('')}<section class="price-card"><h2>Acesso VIP · demonstração</h2><p>Valor ilustrativo</p><div class="price">R$ <strong>19</strong>,90</div><p>Pagamento único simulado · nenhuma cobrança</p><ul><li>Prévia de mídias fictícias</li><li>Mensagens de exemplo</li><li>Fluxo de checkout demonstrativo</li></ul><button class="primary" data-checkout>Simular acesso VIP</button><small>Não libera dados privados de nenhuma conta.</small></section></main><footer class="purchase-bar"><div><b>Checkout demonstrativo</b><small>Nenhum valor será cobrado.</small></div><button class="primary" data-checkout>Simular acesso agora</button></footer>`;
  const page = document.body.dataset.page;
  $('#app').innerHTML = page === 'feed' ? feed() : page === 'direct' ? direct() : cta();
  const dialog = document.createElement('dialog'); dialog.className = 'demo-dialog'; document.body.append(dialog);
  const open = body => { dialog.innerHTML = `<button class="close" aria-label="Fechar">×</button>${body}`; dialog.querySelector('.close').onclick = () => dialog.close(); dialog.showModal(); };
  const notice = text => { const toast = $('#toast'); toast.textContent = text; toast.hidden = false; clearTimeout(notice.timer); notice.timer = setTimeout(()=>toast.hidden=true,3000); };
  document.addEventListener('click', e => {
    const button = e.target.closest('button'); if (!button) return;
    if (button.hasAttribute('data-like') || button.hasAttribute('data-repost') || button.hasAttribute('data-save')) {
      const on = button.getAttribute('aria-pressed') !== 'true'; button.setAttribute('aria-pressed',String(on));
      if (button.hasAttribute('data-like')) { const count = button.closest('.post').querySelector('.like-count'); count.textContent = `${parseInt(count.textContent)+(on?1:-1)} curtidas`; }
    }
    if (button.hasAttribute('data-comment')) {
      const post = button.closest('.post'); open('<h2>Comentar na demonstração</h2><form id="comment-form"><label>Seu comentário<input name="comment" required maxlength="300" placeholder="Adicione um comentário…"></label><button class="primary">Publicar localmente</button></form><small>Fica somente nesta página.</small>');
      $('#comment-form').onsubmit = event => {event.preventDefault(); const p = document.createElement('p'); p.textContent = 'Você: ' + new FormData(event.target).get('comment'); post.querySelector('.comments').append(p); dialog.close();};
    }
    if (button.hasAttribute('data-share')) open('<h2>Compartilhar demonstração</h2><p>Link local para abrir neste computador:</p><input readonly aria-label="Link local" value="http://127.0.0.1:8000/feed.html"><small>Esta ação não envia mensagens.</small>');
    if (button.dataset.notice) notice(button.dataset.notice);
    if (button.hasAttribute('data-chat')) open(`<h2>${names[Number(button.dataset.chat)]}</h2><p class="muted">Conversa fictícia</p><div class="bubble">Oi! Este é um exemplo de mensagem.</div><div class="bubble sent">Vamos testar a interface 🙂</div><div class="chat-lock">${icon('lock')} Conteúdo restrito · demonstração</div><a class="primary" href="paginafinal.html">Ver demonstração VIP</a>`);
    if (button.hasAttribute('data-checkout')) open('<h2>Checkout demonstrativo</h2><p>Acesso VIP · <b>R$ 19,90</b> (valor ilustrativo)</p><div class="payment-method">PIX · simulação</div><p>Nenhum dado pessoal é solicitado. Não há chave PIX nem código pagável.</p><button class="primary" data-generate>Gerar pagamento simulado</button>');
    if (button.hasAttribute('data-generate')) open('<h2>Pagamento simulado</h2><div class="fake-qr">DEMO<br>SEM QR PAGÁVEL</div><p>Este exemplo não pode ser pago.</p><button class="primary" data-paid>Simular confirmação</button>');
    if (button.hasAttribute('data-paid')) open('<div class="success">✓</div><h2>Simulação concluída</h2><p>Nenhum pagamento foi processado e nenhum conteúdo privado foi liberado.</p><a class="primary" href="feed.html">Voltar ao feed</a>');
  });
})();
